development:
  adapter: mysql2
  database: etl
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8

production:
  adapter: mysql2
  database: etl
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8
  prepared_statements: false

